### ISSUE TITLE
PollfishSurveyClosedListener does not work on iOs

### ISSUE THREAD

**Issue by jennsenr** [pollfish/flutter-plugin-pollfish#8] opened 2020-06-11 18:34 UTC
```dart 
FlutterPollfish.instance.setPollfishSurveyClosedListener(onPollfishSurveyClosed);

void onPollfishSurveyClosed() {
    FlutterPollfish.instance.hide();
    ExtendedNavigator.rootNavigator.pushReplacementNamed(Routes.introPage);
  }
```

This works well on Android but on iOS it does not respond to the listener, on the console it says

`Unknown method pollfishSurveyClosedSurvey`

**Comment by kaspanvo** [comment] 2020-06-12 09:53
the issue is fixed in the new release v1.0.5

**Closed by kaspanvo** 2020-06-12 09:53 UTC
