### ISSUE TITLE
issue with CocoaPods with iOS

### ISSUE THREAD

**Issue by nitneuq33000** [pollfish/flutter-plugin-pollfish#7] opened 2020-03-31 15:41 UTC
Hello, I push pollfish on my android APP, with no problem. I try to migrate this in my iOS app but I have this error.

```
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A Pollfish
      A flutter_pollfish
      - Flutter
      - app_review
      - audioplayers
      - firebase_admob
      - firebase_core
      - firebase_core_web
      - flutter_barcode_scanner
      - flutter_email_sender
      - flutter_rounded_progress_bar
      - flutter_youtube_view
      - in_app_purchase
      - package_info
      - path_provider
      - screenshot_share_image
      - sensors
      - shared_preferences
      - unique_identifier
      - url_launcher
      - vibration
      - webview_media

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `app_review` from `.symlinks/plugins/app_review/ios`
    -> Fetching podspec for `audioplayers` from `.symlinks/plugins/audioplayers/ios`
    -> Fetching podspec for `firebase_admob` from `.symlinks/plugins/firebase_admob/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_core_web` from `.symlinks/plugins/firebase_core_web/ios`
    -> Fetching podspec for `flutter_barcode_scanner` from `.symlinks/plugins/flutter_barcode_scanner/ios`
    -> Fetching podspec for `flutter_email_sender` from `.symlinks/plugins/flutter_email_sender/ios`
    -> Fetching podspec for `flutter_pollfish` from `.symlinks/plugins/flutter_pollfish/ios`
    -> Fetching podspec for `flutter_rounded_progress_bar` from `.symlinks/plugins/flutter_rounded_progress_bar/ios`
    -> Fetching podspec for `flutter_youtube_view` from `.symlinks/plugins/flutter_youtube_view/ios`
    -> Fetching podspec for `in_app_purchase` from `.symlinks/plugins/in_app_purchase/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `screenshot_share_image` from `.symlinks/plugins/screenshot_share_image/ios`
    -> Fetching podspec for `sensors` from `.symlinks/plugins/sensors/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `unique_identifier` from `.symlinks/plugins/unique_identifier/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `vibration` from `.symlinks/plugins/vibration/ios`
    -> Fetching podspec for `webview_media` from `.symlinks/plugins/webview_media/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "Pollfish":
      In Podfile:
        Pollfish

        flutter_pollfish (from `.symlinks/plugins/flutter_pollfish/ios`) was resolved to 1.0.1, which depends on
          Pollfish (~> 5.2.5)

    Specs satisfying the `Pollfish, Pollfish (~> 5.2.5)` dependency were found, but they required a higher minimum deployment target.

    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:88:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:398:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

```

There is no additional modification between android and iOS in the description of the package. Why this error ? thank you

**Comment by kaspanvo** [comment] 2020-03-31 15:47
_**Specs satisfying the `Pollfish, Pollfish (~> 5.2.5)` dependency were found, but they required a higher minimum deployment target.**_


What is your minimum deployment target?

**Comment by nitneuq33000** [comment] 2020-03-31 15:53
[image: image.png]
ios 11, It's this ?

**Comment by kaspanvo** [comment] 2020-04-01 07:12
Pollfish minimum deployment target is iOS 9 as you may see in the relevant podspec on CocoaPods https://github.com/CocoaPods/Specs/blob/master/Specs/e/1/f/Pollfish/5.2.5/Pollfish.podspec.json

Are you sure that you do not have a lower minimum than that? Can you share your own podspec?

**Comment by kaspanvo** [comment] 2020-04-01 07:28
image attached is not shown also..

**Comment by nitneuq33000** [comment] 2020-04-01 07:37
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting
flutter build latency.

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have
something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version
of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before
any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path =
File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod
install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings =
parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir =
generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir,
'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'),
copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and
causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

**Comment by nitneuq33000** [comment] 2020-04-01 07:38
picture show xcode -> general -> deployement info->Targer->  ios11.0

**Comment by kaspanvo** [comment] 2020-04-02 15:20
not sure what is the issue since Pollfish pod has a minimum of iOS 9.

Can you try something please? In the top of your podspec file can you uncomment this:
# platform :ios, '9.0'

and see if the issue is resolved?

**Comment by nitneuq33000** [comment] 2020-04-02 16:24
I have this error.


CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A flutter_pollfish
      - Flutter
      - app_review
      - audioplayers
      - firebase_admob
      - firebase_core
      - firebase_core_web
      - flutter_barcode_scanner
      - flutter_email_sender
      - flutter_rounded_progress_bar
      - flutter_youtube_view
      - in_app_purchase
      - package_info
      - path_provider
      - screenshot_share_image
      - sensors
      - shared_preferences
      - unique_identifier
      - url_launcher
      - vibration
      - webview_media

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `app_review` from `.symlinks/plugins/app_review/ios`
    -> Fetching podspec for `audioplayers` from `.symlinks/plugins/audioplayers/ios`
    -> Fetching podspec for `firebase_admob` from `.symlinks/plugins/firebase_admob/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_core_web` from `.symlinks/plugins/firebase_core_web/ios`
    -> Fetching podspec for `flutter_barcode_scanner` from `.symlinks/plugins/flutter_barcode_scanner/ios`
    -> Fetching podspec for `flutter_email_sender` from `.symlinks/plugins/flutter_email_sender/ios`
    -> Fetching podspec for `flutter_pollfish` from `.symlinks/plugins/flutter_pollfish/ios`
    -> Fetching podspec for `flutter_rounded_progress_bar` from `.symlinks/plugins/flutter_rounded_progress_bar/ios`
    -> Fetching podspec for `flutter_youtube_view` from `.symlinks/plugins/flutter_youtube_view/ios`
    -> Fetching podspec for `in_app_purchase` from `.symlinks/plugins/in_app_purchase/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `screenshot_share_image` from `.symlinks/plugins/screenshot_share_image/ios`
    -> Fetching podspec for `sensors` from `.symlinks/plugins/sensors/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `unique_identifier` from `.symlinks/plugins/unique_identifier/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `vibration` from `.symlinks/plugins/vibration/ios`
    -> Fetching podspec for `webview_media` from `.symlinks/plugins/webview_media/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "Pollfish":
      In Podfile:
        flutter_pollfish (from `.symlinks/plugins/flutter_pollfish/ios`) was resolved to 1.0.1, which depends on
          Pollfish (~> 5.2.5)

    None of your spec sources contain a spec satisfying the dependency: `Pollfish (~> 5.2.5)`.

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.

    Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:88:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:398:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

**Comment by kaspanvo** [comment] 2020-04-03 09:57
Can try to delete Podfile.lock And then run pod update?

**Comment by nitneuq33000** [comment] 2020-04-03 10:48
It's seems OK with pod repo update, I will continue to test if all is OK .
Thank you

**Comment by kaspanvo** [comment] 2020-04-03 10:52
Ok great, we are closing the issue for the moment. Please let us know if problem persists

**Closed by kaspanvo** 2020-04-03 10:52 UTC
